services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKlee\Oelib\:
    resource: '../Classes/*'
    exclude: '../Classes/DataStructures/*,../Classes/Domain/Model/*,../Classes/Model/*'
