services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKlee\Oelib\:
    resource: '../Classes/Domain/Repository/*,../Classes/Geocoding/*,../Classes/Http/*,../Classes/Mapper/*'
