name: automerge

on:
  pull_request

jobs:
  automerge:
    name: Dependabot auto-merge

    runs-on: ubuntu-22.04

    timeout-minutes: 1

    permissions:
      pull-requests: write

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Enable PR automerge
        run: gh pr merge --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
